apiVersion: v1
kind: Service
metadata:
  name: swiggy-service
  labels:
    app: swg
spec:
  type: ClusterIP
  selector:
    app: swg
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  
